-- Fresh demo seed for the new 8-group / 31-sub taxonomy. Wipes the
-- prior demo set (which was migrated from the old flat 28-category
-- list and had gaps after wedding-only deletions) and seeds exactly
-- one demo vendor per sub-category.
--
-- Every row is_demo = true and application_status = 'approved' so
-- they show up in the public directory. user_id stays null — these
-- aren't real auth users; the user_id NOT NULL constraint was
-- dropped earlier in 20260505213616_*.sql for exactly this reason.
--
-- category_attributes JSONB is populated against the per-group
-- schemas in src/data/categoryAttributes.ts, so the public profile
-- "About this {sub}" section renders meaningfully for every demo.
-- Hot fields (max_guests, package_starting_cents) are also kept here
-- so directory filters that promote them later don't need a backfill.

-- 1. Delete the prior demo set so the seed below is idempotent.
delete from public.vendor_profiles where is_demo;

-- 2. Insert 31 demos — one per sub-category, spread across 14 cities.
insert into public.vendor_profiles (
  user_id, business_name, category, bio, base_price_cents,
  location, service_radius_miles, portfolio_summary, verified_at,
  application_status, is_demo, category_attributes
) values
-- ─── Venues (4) ────────────────────────────────────────────────────
  (null, 'The Hayloft at Crooked Creek', 'Event Venues',
   'A restored 1890s dairy barn on 80 acres in the Hudson Valley — the kind of place where the architecture does the decorating for you.',
   600000, 'Hudson Valley, NY', 90,
   'Renovated barn + ceremony field + 6 on-site cabins. Hosts 50-200 guests. In-house bar, planning, and design team.',
   now(), 'approved', true,
   '{"reception_starting_cents":600000,"ceremony_starting_cents":250000,"max_guests":200,"min_guests":50,"settings":["Farm & Ranch","Historic","Estate"],"amenities":["Indoor Event Space","Outdoor Event Space","Covered Outdoor Space","Bridal Suite","On-Site Accommodations","Parking","Liquor License","Kitchen"],"service_offerings":["Bar & Drinks","Planning","Service Staff"]}'::jsonb),
  (null, 'Wildhaven Field & Orchard', 'Outdoor Spaces',
   'A working apple orchard with three ceremony fields, a redwood reception meadow, and the kind of golden hour you book a wedding for.',
   450000, 'Sonoma, CA', 60,
   'Outdoor-only venue. Ceremony fields, reception meadow, ancillary tent permitted. Capacity 40-220.',
   now(), 'approved', true,
   '{"reception_starting_cents":450000,"ceremony_starting_cents":200000,"max_guests":220,"min_guests":40,"settings":["Garden","Vineyard","Trees","Estate"],"amenities":["Ceremony Area","Reception Area","Outdoor Event Space","Parking","Pet Friendly"],"service_offerings":["Tents","Rentals & Equipment"]}'::jsonb),
  (null, 'Theodora Private Dining Room', 'Private Dining Spaces',
   'Oak-paneled dining room above one of Manhattan''s longest-running French bistros. Seats 30 plated, 50 cocktail.',
   200000, 'Manhattan, NY', 20,
   'Reservation-only private room. Plated dinners, rehearsal dinners, milestone celebrations. F&B minimum applies.',
   now(), 'approved', true,
   '{"couples_typical_spend_cents":350000,"max_guests":50,"min_guests":12,"settings":["Restaurant","Historic","Modern"],"amenities":["Indoor Event Space","Wireless Internet","Liquor License","Kitchen"],"service_offerings":["Bar & Drinks","Catering","Service Staff"]}'::jsonb),
  (null, 'The Ledger Conference Hall', 'Corporate / Conference Spaces',
   'Tech-forward 200-capacity venue with breakout rooms, AV bundled, and a rooftop terrace for receptions.',
   180000, 'Austin, TX', 30,
   'Day rates Mon-Fri, evening rates available. AV + WiFi + concierge included.',
   now(), 'approved', true,
   '{"reception_starting_cents":180000,"max_guests":200,"min_guests":20,"settings":["Modern","Industrial","Rooftop"],"amenities":["Indoor Event Space","Outdoor Event Space","Wireless Internet","Parking","Handicap Accessible"],"service_offerings":["Bar & Drinks","Catering","Rentals & Equipment","Service Staff"]}'::jsonb),

-- ─── Food & Beverage (4) ──────────────────────────────────────────
  (null, 'Garden Table Catering', 'Catering',
   'Seasonal, hyper-local cooking for weddings and private dinners. Multi-course tasting menus or elevated family-style.',
   12500, 'Hudson Valley, NY', 100,
   'Per-head pricing varies. Farm-to-table multi-course dinners and elevated buffets.',
   now(), 'approved', true,
   '{"per_person_starting_cents":12500,"event_minimum_cents":500000,"max_guests":250,"min_guests":20,"service_styles":["Plated","Family-style","Tasting menu","Stations"],"cuisines":["Farm-to-table","American","Mediterranean","Vegetarian-forward"],"dietary":["Vegetarian","Vegan","Gluten-free","Allergen-aware"],"included_services":["Setup & breakdown","Service staff","Tasting included","Linens"]}'::jsonb),
  (null, 'Last Call Bar Co.', 'Bartending / Mobile Bars',
   'Mobile bar service — licensed, insured bartenders for weddings, milestone parties, and corporate events.',
   8500, 'Austin, TX', 100,
   'Hourly per bartender, 4-hour minimum. Custom cocktail menus.',
   now(), 'approved', true,
   '{"hourly_rate_cents":8500,"event_minimum_cents":50000,"bar_services":["Full bar","Cocktails — custom menu","Cocktails — house menu","Mocktails","Glassware provided","Bar setup / breakdown","Liquor license"],"byob_friendly":true,"tabc_riservi_certified":true,"dietary":["Allergen-aware"]}'::jsonb),
  (null, 'Levain & Co. Patisserie', 'Desserts & Cakes',
   'Sculptural wedding cakes and French pastry dessert tables. Custom flavors, seasonal fillings.',
   45000, 'Brooklyn, NY', 60,
   'Custom flavors, seasonal fillings. Nut-free and gluten-free options available.',
   now(), 'approved', true,
   '{"per_person_starting_cents":1200,"event_minimum_cents":45000,"dessert_offerings":["Wedding / event cakes","Macarons","Tarts","Pastry tables","Plated desserts"],"custom_flavors":true,"dietary":["Vegetarian","Gluten-free","Dairy-free","Nut-free","Allergen-aware"]}'::jsonb),
  (null, 'Smoke Stack BBQ Truck', 'Food Trucks / Specialty',
   'Texas-style brisket, ribs, and house-pickled sides served from a 22-foot custom truck — receptions, corporate parks, weddings.',
   250000, 'Nashville, TN', 200,
   'Truck plus on-site grill stations. Family-style or single-serve. Vegetarian + GF sides standard.',
   now(), 'approved', true,
   '{"per_person_starting_cents":3500,"event_minimum_cents":250000,"max_guests":300,"truck_length_feet":22,"off_grid_capable":true,"permitted_in_state":true,"cuisines":["American","Southern / BBQ"],"dietary":["Vegetarian","Gluten-free"],"included_services":["Setup & breakdown","Disposables","Service staff"]}'::jsonb),

-- ─── Entertainment (4) ────────────────────────────────────────────
  (null, 'Kindred Sound', 'DJs',
   'Wedding DJs with a curator''s ear — soul, R&B, house, and the open-format reads that turn dance floors into stories.',
   220000, 'Charlotte, NC', 150,
   '4-hour reception standard. MC services + uplighting included.',
   now(), 'approved', true,
   '{"package_starting_cents":220000,"hourly_rate_cents":35000,"default_set_hours":4,"max_set_hours":8,"mc_services_included":true,"uplighting_included":true,"takes_requests":true,"dj_genres":["Soul","Hip-hop / R&B","House","Open format","Top 40","Pop"],"owns_equipment":true,"outdoor_capable":true,"setup_minutes":60}'::jsonb),
  (null, 'The Sundowners', 'Live Music',
   '6-piece live band with horn section and male/female leads. Ceremony acoustic, cocktail trio, full reception.',
   650000, 'Nashville, TN', 200,
   'Ceremony acoustic, cocktail trio, full reception. PA + lighting included.',
   now(), 'approved', true,
   '{"package_starting_cents":650000,"default_set_hours":4,"max_set_hours":6,"ensemble_size":6,"ensemble_format":["Full band (5-7)","Trio","Acoustic"],"music_genres":["Soul / Motown","Pop","Rock","R&B","Country"],"pa_lighting_included":true,"owns_equipment":true,"setup_minutes":90}'::jsonb),
  (null, 'Lumen Aerial Arts', 'Performers',
   'Aerial silk dancers, hoop performers, and choreographed sequences for galas, brand activations, and reception entertainment.',
   180000, 'Los Angeles, CA', 100,
   '15-30 minute custom sets. Rigging consult included. Professional aerialists, fully insured.',
   now(), 'approved', true,
   '{"package_starting_cents":180000,"set_minutes":20,"performance_types":["Aerialists","Dancers","Stilt walkers"],"owns_equipment":true,"outdoor_capable":true,"setup_minutes":120}'::jsonb),
  (null, 'Olivia Reyes Hosting', 'Hosts / MCs',
   'Bilingual emcee for weddings, galas, and corporate awards. Calm, prepped, and reads the room — never over-talks.',
   150000, 'Miami, FL', 250,
   'Custom run-of-show, ceremony script support, on-mic for receptions and award programs.',
   now(), 'approved', true,
   '{"package_starting_cents":150000,"hourly_rate_cents":35000,"default_set_hours":4,"mc_languages":["English","Spanish","Bilingual emcee","Portuguese"],"mc_event_specialties":["Weddings","Galas / fundraisers","Corporate / awards","Auctions","Brand activations"]}'::jsonb),

-- ─── Media (3) ────────────────────────────────────────────────────
  (null, 'Aurora Lane Studios', 'Photography',
   'Documentary-style wedding photography that prioritizes the in-between moments — the candid hug, the quiet exit, the second laugh.',
   350000, 'Brooklyn, NY', 200,
   'Editorial + documentary work for weddings. Two-shooter weekends standard.',
   now(), 'approved', true,
   '{"package_starting_cents":350000,"engagement_shoot_starting_cents":75000,"travel_fee_starts_at_miles":50,"default_coverage_hours":8,"team_size":2,"second_shooter_available":true,"gallery_delivery_weeks":4,"photo_styles":["Documentary","Editorial","Photojournalism","Modern","Bright & Airy"],"photo_deliverables":["Digital files (high-res)","Online gallery","Print release included","Albums available","Same-day teasers"],"destination_friendly":true}'::jsonb),
  (null, 'Reverie Films', 'Videography',
   'Cinematic wedding films that play like a short documentary. Multi-camera, drone, the works.',
   500000, 'Austin, TX', 150,
   'Two-videographer crew. Highlight reel + extended cut delivered in 8 weeks.',
   now(), 'approved', true,
   '{"package_starting_cents":500000,"travel_fee_starts_at_miles":75,"default_coverage_hours":8,"team_size":2,"second_shooter_available":true,"final_delivery_weeks":8,"video_styles":["Cinematic","Documentary","Storytelling","Drone-focused"],"video_deliverables":["Highlight reel (3-5 min)","Extended highlight (8-15 min)","Full ceremony / event cut","Toasts / speeches cut","Drone footage","Multi-camera"],"destination_friendly":true}'::jsonb),
  (null, 'Snapshot Social Booths', 'Photo Booths',
   'Open-air and mirror photo booths with custom branded backdrops, instant prints, and shareable digital galleries.',
   95000, 'Los Angeles, CA', 75,
   '3-hour minimum, attendant included. Prop kits, custom overlays, GIF mode available.',
   now(), 'approved', true,
   '{"package_starting_cents":95000,"booth_types":["Open-air","Mirror","GIF / video","360 booth"],"booth_min_hours":3,"booth_attendant_included":true,"instant_prints":true,"custom_overlays":true,"digital_gallery_after":true,"destination_friendly":false}'::jsonb),

-- ─── Design & Decor (5) ───────────────────────────────────────────
  (null, 'North Field Events', 'Event Coordinators',
   'Full-service planning for weddings of 80-300 guests — vendor management, run-of-show, day-of staffing.',
   800000, 'Hudson Valley, NY', 150,
   'Full, partial, and month-of coordination tiers. Average booking 9-14 months out.',
   now(), 'approved', true,
   '{"package_starting_cents":800000,"planning_tiers":["Full-service planning","Partial planning","Month-of","Day-of coordination","Design only"],"coordination_services":["Vendor management","Run-of-show","Budget tracking","Timeline build","Site walks","Rehearsal direction","Day-of staffing"],"max_concurrent_events":3,"destination_friendly":true}'::jsonb),
  (null, 'Bloom & Bough', 'Florists',
   'Garden-style installations and seasonal florals. Locally-sourced when possible, sculptural when required.',
   180000, 'Asheville, NC', 100,
   'Locally-sourced. Sculptural arches, loose centerpieces, full design.',
   now(), 'approved', true,
   '{"package_starting_cents":180000,"minimum_order_cents":150000,"floral_styles":["Garden","Modern","Wild / asymmetric","Romantic"],"floral_offerings":["Personal flowers (bouquets / boutonnières)","Centerpieces","Ceremony arches / installations","Hanging installations","Aisle florals","Welcome / entry pieces","Sustainable / locally-sourced"],"delivery_included":true,"destination_friendly":false}'::jsonb),
  (null, 'Veil Beauty Lab', 'Beauty',
   'On-location bridal beauty — hair, makeup, lashes, brow shaping, skin prep. Trial included with weekend bookings.',
   95000, 'Chicago, IL', 75,
   'Hair, makeup, lashes, brows, skin prep — full bridal beauty team. Engagement-shoot prep available.',
   now(), 'approved', true,
   '{"package_starting_cents":95000,"trial_cost_cents":15000,"beauty_services":["Hair styling","Makeup","Airbrush makeup","Lash extensions","Brow shaping","Skin prep","Updo / blowout","Touch-ups on-site"],"trial_included":true,"on_location_only":true,"max_artists_on_team":4}'::jsonb),
  (null, 'Set Design Co.', 'Decor Rentals',
   'Tablescape, lighting, signage, and full event styling. Editorial-grade specs delivered + executed.',
   250000, 'Brooklyn, NY', 80,
   'Editorial-grade decor specs delivered + executed. Custom builds on commission.',
   now(), 'approved', true,
   '{"package_starting_cents":250000,"minimum_order_cents":150000,"decor_inventory":["Tabletop / centerpieces","Linens","Lighting","Signage","Backdrops","Arches","Aisle decor","Lounge furniture","Candles","Custom builds"],"decor_aesthetic":["Modern","Editorial","Romantic","Minimal","Industrial"],"delivery_included":true,"destination_friendly":false}'::jsonb),
  (null, 'Sharp & Co. Grooming', 'Grooming Services',
   'On-location grooming for grooms and groomsmen — haircuts, beard trims, hot-towel shaves the morning of.',
   35000, 'San Francisco, CA', 60,
   'Mobile barber team. Full party 4-8 grooms, individual sessions also booked.',
   now(), 'approved', true,
   '{"package_starting_cents":35000,"trial_cost_cents":7500,"grooming_services":["Haircut","Beard trim","Hot-towel shave","Hair styling","Skin prep","On-location"]}'::jsonb),

-- ─── Rentals (5) ──────────────────────────────────────────────────
  (null, 'Bloom Hill Rentals', 'Furniture Rentals',
   'Lounge furniture, farm tables, mismatched chairs, and editorial tabletop in stock for events of every size.',
   50000, 'Hudson Valley, NY', 150,
   'Tables, chairs, lounge groupings, glassware, flatware. Same-day delivery within metro.',
   now(), 'approved', true,
   '{"order_minimum_cents":50000,"delivery_starting_cents":20000,"inventory_categories":["Tables (round / banquet)","Chairs (folding / chiavari)","Lounge furniture","Linens","Bars"],"furniture_styles":["Modern","Classic","Vintage","Lounge","Outdoor / weather-resistant"],"delivery_setup_breakdown":true,"service_radius_miles":75}'::jsonb),
  (null, 'Sailcloth Co.', 'Tents & Outdoor',
   'Hand-stitched sailcloth tents — the kind of structure that makes the venue. Pole, frame, sperry, clear span.',
   800000, 'Charleston, SC', 250,
   'White-glove tent installation including engineering, sub-flooring, sidewalls, lighting integration.',
   now(), 'approved', true,
   '{"order_minimum_cents":800000,"delivery_starting_cents":150000,"inventory_categories":["Tents","Tent flooring","Lighting"],"tent_types":["Pole tent","Frame tent","Sailcloth","Clear span","Sperry / sailcloth"],"tent_max_capacity":350,"tent_sidewalls_available":true,"tent_flooring_available":true,"delivery_setup_breakdown":true,"service_radius_miles":250}'::jsonb),
  (null, 'Ember & Pulse AV', 'Lighting & AV Equipment',
   'Concert-grade audio, uplighting, gobo projection, and live-stream rigs for weddings, galas, and corporate events.',
   250000, 'Miami, FL', 200,
   'Sound, lighting, video, and live-stream packages. AV tech on-site for every booking.',
   now(), 'approved', true,
   '{"order_minimum_cents":250000,"delivery_starting_cents":50000,"inventory_categories":["Lighting","Audio / PA","Video / projection"],"av_offerings":["Uplighting","String / café lights","Pin-spotting","Gobo / monogram projection","Stage lighting","Microphones (wired / wireless)","PA systems","Mixers","Projection screens","LED walls","Live-stream rigs"],"av_tech_on_site":true,"delivery_setup_breakdown":true}'::jsonb),
  (null, 'Stage Hands Co.', 'Dance Floors & Staging',
   'Custom-decal dance floors, modular stages, and seamless under-ceremony platforms for weddings and brand activations.',
   180000, 'Las Vegas, NV', 200,
   'Black, white, parquet, custom decals + LED panels. Modular staging from 8x8 to full ballroom.',
   now(), 'approved', true,
   '{"order_minimum_cents":180000,"delivery_starting_cents":75000,"inventory_categories":["Dance floor","Staging"],"floor_types":["Wood parquet","Black","White","LED illuminated","Custom decal","Outdoor sub-floor"],"stage_types":["Risers (8-24in)","Modular stage","Skirted stage","Curtain backdrops"],"delivery_setup_breakdown":true}'::jsonb),
  (null, 'Heritage Limousine Service', 'Transportation',
   'Vintage Rolls-Royce, Mercedes coaches, and shuttle coordination for guest movement and getaway moments.',
   35000, 'Charlotte, NC', 100,
   'Hourly per vehicle. 3-hour minimum. Professional, uniformed chauffeurs.',
   now(), 'approved', true,
   '{"delivery_starting_cents":15000,"inventory_categories":[],"vehicle_types":["Sedan","SUV","Limousine","Stretch limo","Mini-bus (15-25 pax)","Coach (30-55 pax)","Vintage car"],"fleet_size":18,"min_booking_hours":3,"chauffeur_uniformed":true}'::jsonb),

-- ─── Experiences (2) ──────────────────────────────────────────────
  (null, 'The Cellar Sommelier Co.', 'Tastings',
   'Guided wine, champagne, and whiskey tastings led by certified sommeliers. 60-90 minute education + pour programs.',
   45000, 'Sonoma, CA', 200,
   'Guided pours, food pairings, and education for receptions, corporate offsites, milestone events.',
   now(), 'approved', true,
   '{"per_person_starting_cents":7500,"event_minimum_cents":45000,"min_guest_count":10,"tasting_types":["Wine","Champagne / sparkling","Whiskey / bourbon","Tequila / mezcal","Cheese","Chocolate"],"sommelier_certified":true,"guided_education":true,"default_service_hours":2,"outdoor_capable":true,"bilingual_staff":true}'::jsonb),
  (null, 'Smoke + Spirits Cigar Service', 'Specialty Services',
   'Roaming cigar rollers, paired bourbon flights, and lounge build-outs — the "wow" hour at receptions and post-dinner programs.',
   200000, 'Miami, FL', 150,
   'Cigar rollers + lounge furniture + bourbon flight included. 2-hour standard service.',
   now(), 'approved', true,
   '{"per_person_starting_cents":4500,"event_minimum_cents":200000,"min_guest_count":20,"specialty_offerings":["Cigar rolling","Custom cocktail bar","Coffee cart","Espresso bar"],"default_service_hours":2,"outdoor_capable":true}'::jsonb),

-- ─── Corporate Services (4) ──────────────────────────────────────
  (null, 'Set the Table Hospitality', 'Staffing',
   'Trained service staff for plated dinners, passed-canape receptions, and high-touch corporate events.',
   7500, 'Brooklyn, NY', 80,
   'Hourly per server. 4-hour minimum. Uniforms standard, fine-dining trained.',
   now(), 'approved', true,
   '{"hourly_rate_cents":7500,"min_booking_hours":4,"staffing_roles":["Servers","Bartenders","Bussers","Greeters / coat check","Captains","Setup / breakdown crew","Day-of coordinators","Registration / check-in"],"uniforms_provided":true,"trained_in_fine_dining":true,"background_checked_staff":true,"event_specialties":["Weddings","Galas / fundraisers","Corporate / awards","Brand activations","Private estates"]}'::jsonb),
  (null, 'Voicewise Speakers Bureau', 'Speakers / Hosts',
   'Curated keynote speakers and panel moderators for corporate events, conferences, and award programs.',
   1500000, 'San Francisco, CA', 0,
   'Speaker placement + content prep + run-of-show review. Roster includes Fortune 500 alumni and academic experts.',
   now(), 'approved', true,
   '{"package_starting_cents":1500000,"min_booking_hours":1,"speaker_topics":["Leadership","Diversity & inclusion","Innovation / tech","Sales","Marketing","Wellness","Finance","Climate / sustainability"],"speaker_formats":["Keynote","Fireside chat","Panel moderator","Workshop","Master class","Awards host / emcee"],"host_languages":["English","Spanish","Mandarin","French"],"event_specialties":["Conferences","Galas / fundraisers","Corporate / awards"]}'::jsonb),
  (null, 'Guardline Event Security', 'Security',
   'Licensed event security — access control, crowd management, VIP protection. Plainclothes or uniformed.',
   8500, 'Charlotte, NC', 150,
   'Plainclothes or uniformed. 6-hour minimum. Insured + bonded.',
   now(), 'approved', true,
   '{"hourly_rate_cents":8500,"min_booking_hours":6,"security_services":["Access control","Crowd management","VIP protection","Bag checks","Plainclothes","Uniformed","Unarmed"],"licensed_in_state":true,"background_checked_staff":true,"event_specialties":["Corporate / awards","Galas / fundraisers","Concerts / festivals","Private estates"]}'::jsonb),
  (null, 'Premier Valet Group', 'Valet',
   'Insured valet teams for venues without on-site parking. Coordinated podium, key boxes, shuttle planning.',
   7000, 'Atlanta, GA', 100,
   'Hourly per attendant. Includes podium, key boxes, shuttle coordination.',
   now(), 'approved', true,
   '{"hourly_rate_cents":7000,"min_booking_hours":4,"valet_attendants_typical":6,"valet_podium_keys_provided":true,"valet_shuttle_coordination":true,"valet_insured":true,"background_checked_staff":true,"event_specialties":["Weddings","Galas / fundraisers","Corporate / awards","Private estates"]}'::jsonb);
